### ISSUE TITLE
License

### ISSUE THREAD

**Issue by leftshift** [starenka/chordata#2]
Hey, I'd love to use this in an open-source project I'm working on, but unfortunatly, this project doesn't have any clear license, so I'm reluctant to use it. I'd be super happy if you could change that.
Thanks.

**Comment by starenka** [comment]
Hi, I don't dig too much license lore. Take it as it has the most permissive one which exists ;)

**Comment by leftshift** [comment]
Alright, thanks :+1:

**Comment by starenka** [comment]
Just out of curiosity, could you share the project then? Cheers

**Comment by leftshift** [comment]
I might use it in https://github.com/leftshift/tabload

starenka <notifications@github.com> schrieb am Mo., 19. Juni 2017, 14:20:

**Comment by starenka** [comment]
Nice! Will keep an eye on that, looks like a good idea!
